title: "Vaaruni Desai"
description: "AI Research - Interpretability, Alignment, Training Dynamics"
url: "https://vaarunidesai.github.io"
baseurl: ""
theme: minima
paginate: 5
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
# Social links
linkedin_username: https://www.linkedin.com/in/vaaruni-desai/
github_username: https://github.com/Vaaruni2797
email: vaaruni.desai@gmail.com
medium: https://medium.com/@vaaruni.desai
title: "Vaaruni Desai"
description: "AI Research â€” Interpretability, Alignment, Training Dynamics"
