title: "Vaaruni Desai"
description: "AI Research â€” Interpretability, Alignment, Training Dynamics"

# IMPORTANT: this is your actual GitHub Pages domain
url: "https://vaaruni2797.github.io"

# IMPORTANT: this is your repo name, with a leading slash
baseurl: "/vaarunidesai.github.io"

theme: minima

paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
