title: "Vaaruni Desai"
description: "AI Research â€” Interpretability, Alignment, Training Dynamics"

url: "https://vaarunidesai.github.io"
baseurl: ""

theme: minima

paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

linkedin_username: vaaruni-desai
github_username: Vaaruni2797
email: vaaruni.desai@gmail.com
medium: vaaruni.desai
